version: '3.2'
services:
  zkstack-core:
    container_name: zkstack-core
    image: kedavra/haya-zk:v0.1
    command: ["--components", "tree,eth,state_keeper,housekeeper,proof_data_handler"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3071/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - ${HAYA_ENV}
    environment:
      ZKSYNC_HOME: /
    ports: # assumes default ports in .env
      #- "3312:3312" # prometheus metrics # we need a separate metrics port for each component
      - "3320:3320" # proof_data_handler api
    volumes:
      - type: bind
        source: ${ENV_DIR}
        target: /home/ubuntu/zksync-era/etc/env
      - type: bind
        source: ./volumes/reth/data
        target: /rethdata
      - type: bind
        source: ./volumes/reth/chaindata
        target: /chaindata

  zkstack-apis:
    image: kedavra/haya-zk:v0.1
    command: ["--components", "http_api,ws_api"]
    env_file:
      - ./etc/env/haya.env
    volumes:
      - type: bind
        source: ${ENV_DIR}
        target: /home/ubuntu/zksync-era/etc/env
    environment:
      ZKSYNC_HOME: /
      FRI_PROVER_GATEWAY_API_URL: http://zkstack-core:3320
    ports: # assumes default ports in .env
      - "3071:3071" # health
      - "3312:3312" # prometheus metrics # we need a separate metrics port for each component
      - "3050:3050" # http_api
      - "3051:3051" # ws_api
